repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # La versión específica del repositorio de hooks que deseas utilizar
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3.11
        args: [--line-length, '88']
